"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 10:31:35.161428
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('student', 'admin', name='role', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('achievements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.Enum('hackathon', 'competition', 'workshop', 'internship', 'research', 'award', 'other', name='achievementtype', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('organization', sa.String(length=160), nullable=False),
    sa.Column('result', sa.String(length=160), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('achieved_on', sa.Date(), nullable=False),
    sa.Column('evidence_url', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_achievements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievements'))
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievements_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_achievements_user_id'), ['user_id'], unique=False)

    op.create_table('activity_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('subject_user_id', sa.Uuid(), nullable=True),
    sa.Column('is_admin_action', sa.Boolean(), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=True),
    sa.Column('summary', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_activity_logs_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_user_id'], ['users.id'], name=op.f('fk_activity_logs_subject_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_logs'))
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_is_admin_action'), ['is_admin_action'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_subject_user_id'), ['subject_user_id'], unique=False)

    op.create_table('certifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('issuer', sa.String(length=160), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('credential_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'verified', 'rejected', name='certstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('file_key', sa.String(length=80), nullable=True),
    sa.Column('file_mime', sa.String(length=80), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('reviewed_by_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status = 'pending' OR (reviewed_by_id IS NOT NULL AND reviewed_at IS NOT NULL)", name=op.f('ck_certifications_review_recorded')),
    sa.CheckConstraint('expiry_date IS NULL OR expiry_date >= issue_date', name=op.f('ck_certifications_dates')),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_certifications_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_certifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certifications'))
    )
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certifications_reviewed_by_id'), ['reviewed_by_id'], unique=False)
        batch_op.create_index('ix_certifications_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_certifications_user_id'), ['user_id'], unique=False)

    op.create_table('learning_goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.Enum('programming', 'dsa', 'ai_ml', 'web', 'databases', 'cloud', 'tools', 'soft_skills', name='skillcategory', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='priority', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'completed', name='goalstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('progress BETWEEN 0 AND 100', name=op.f('ck_learning_goals_progress_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_goals'))
    )
    with op.batch_alter_table('learning_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_goals_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_learning_goals_user_status', ['user_id', 'status'], unique=False)

    op.create_table('placement_assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('coding_dsa', 'aptitude', 'technical', 'communication', 'mock_interview', 'resume_portfolio', name='placementcategory', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('assessed_on', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('max_score > 0', name=op.f('ck_placement_assessments_max_positive')),
    sa.CheckConstraint('score <= max_score', name=op.f('ck_placement_assessments_score_le_max')),
    sa.CheckConstraint('score >= 0', name=op.f('ck_placement_assessments_score_nonneg')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_placement_assessments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_placement_assessments'))
    )
    with op.batch_alter_table('placement_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_placement_assessments_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_placement_user_cat_date', ['user_id', 'category', 'assessed_on'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=True),
    sa.Column('demo_url', sa.String(length=500), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'completed', name='projectstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name=op.f('ck_projects_dates')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_projects_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_user_id'), ['user_id'], unique=False)

    op.create_table('skills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('category', sa.Enum('programming', 'dsa', 'ai_ml', 'web', 'databases', 'cloud', 'tools', 'soft_skills', name='skillcategory', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('level', sa.Enum('beginner', 'intermediate', 'advanced', 'expert', name='skilllevel', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('evidence_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_skills_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills')),
    sa.UniqueConstraint('user_id', 'name', name='user_name')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_user_id'), ['user_id'], unique=False)

    op.create_table('student_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('register_number', sa.String(length=40), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('year_of_study', sa.Integer(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=600), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('resume_url', sa.String(length=500), nullable=True),
    sa.Column('portfolio_username', sa.String(length=30), nullable=True),
    sa.Column('portfolio_public', sa.Boolean(), nullable=False),
    sa.Column('portfolio_sections', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('year_of_study IS NULL OR (year_of_study BETWEEN 1 AND 6)', name=op.f('ck_student_profiles_year_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_student_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_profiles')),
    sa.UniqueConstraint('register_number', name=op.f('uq_student_profiles_register_number')),
    sa.UniqueConstraint('user_id', name=op.f('uq_student_profiles_user_id'))
    )
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_profiles_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profiles_portfolio_username'), ['portfolio_username'], unique=True)
        batch_op.create_index(batch_op.f('ix_student_profiles_year_of_study'), ['year_of_study'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_profiles_year_of_study'))
        batch_op.drop_index(batch_op.f('ix_student_profiles_portfolio_username'))
        batch_op.drop_index(batch_op.f('ix_student_profiles_department'))

    op.drop_table('student_profiles')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_user_id'))
        batch_op.drop_index(batch_op.f('ix_skills_category'))

    op.drop_table('skills')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_user_id'))

    op.drop_table('projects')
    with op.batch_alter_table('placement_assessments', schema=None) as batch_op:
        batch_op.drop_index('ix_placement_user_cat_date')
        batch_op.drop_index(batch_op.f('ix_placement_assessments_user_id'))

    op.drop_table('placement_assessments')
    with op.batch_alter_table('learning_goals', schema=None) as batch_op:
        batch_op.drop_index('ix_learning_goals_user_status')
        batch_op.drop_index(batch_op.f('ix_learning_goals_user_id'))

    op.drop_table('learning_goals')
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certifications_user_id'))
        batch_op.drop_index('ix_certifications_status_created')
        batch_op.drop_index(batch_op.f('ix_certifications_reviewed_by_id'))

    op.drop_table('certifications')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_subject_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_is_admin_action'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_action'))

    op.drop_table('activity_logs')
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievements_user_id'))
        batch_op.drop_index(batch_op.f('ix_achievements_kind'))

    op.drop_table('achievements')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
